#!/usr/bin/env python3
"""
从完整字体的 .h 文件直接提取 chars.txt 中的字符，重新构建干净的 cnfont.h
绕过子集化 TTF 和 fontconvert 对子集的渲染 bug

使用方法：python3 rebuild_cnfont.py
"""

import re

FULL_H = '/Users/yuzhang/M5StickS3/cnfont_full_uint32.h'
CHARS_TXT = '/Users/yuzhang/M5StickS3/chars.txt'
OUTPUT_H = '/Users/yuzhang/M5StickS3/cnfont.h'

def main():
    # 读取 chars.txt（项目用到的字符集）
    with open(CHARS_TXT, 'r') as f:
        keep_chars = set(f.read())
    print(f"保留字符集: {len(keep_chars)} 个")

    # 解析完整字体 .h
    print("解析完整字体...")
    with open(FULL_H, 'r') as f:
        content = f.read()

    # Bitmaps（通用 pattern，匹配任意字体名）
    m = re.search(r'Bitmaps\[\] PROGMEM = \{(.*?)\};', content, re.DOTALL)
    full_bm = bytes(int(b, 16) for b in re.findall(r'0x([0-9A-Fa-f]{2})', m.group(1)))

    # Glyphs
    m = re.search(r'Glyphs\[\] PROGMEM = \{(.*?)\};', content, re.DOTALL)
    full_gl_raw = re.findall(r'\{\s*(\d+),\s*(\d+),\s*(\d+),\s*(\d+),\s*(-?\d+),\s*(-?\d+)\s*\}', m.group(1))
    full_gl = [tuple(int(x) for x in g) for g in full_gl_raw]

    # 从 GFXfont 定义提取 yAdvance
    m = re.search(r'GFXfont\s+\w+\s+PROGMEM\s*=\s*\{[^}]*?,\s*0x([0-9A-Fa-f]+),\s*0x([0-9A-Fa-f]+),\s*(\d+)\s*\}', content)
    first = int(m.group(1), 16)
    last = int(m.group(2), 16)
    yAdvance = int(m.group(3))
    print(f"完整字体: Bitmaps={len(full_bm)}B, Glyphs={len(full_gl)}, first=0x{first:X}, last=0x{last:X}, yAdvance={yAdvance}")

    # 构建新 Bitmaps + Glyphs
    print("构建精简字体...")
    new_bm = bytearray([0x00])  # offset=0 是占位符（1x1 空像素）
    new_gl = []
    kept = 0

    for code in range(first, last + 1):
        idx = code - first
        c = chr(code)

        if c in keep_chars and idx < len(full_gl):
            offset, w, h, adv, xo, yo = full_gl[idx]
            if w > 1 and h > 1:
                size = ((w + 7) // 8) * h
                bitmap = full_bm[offset:offset + size]
                if any(b != 0 for b in bitmap):
                    # 有效字符：追加 bitmap
                    new_offset = len(new_bm)
                    new_bm.extend(bitmap)
                    new_gl.append((new_offset, w, h, adv, xo, yo))
                    kept += 1
                    continue

        # 占位符（不在保留集，或 bitmap 为空）
        new_gl.append((0, 1, 1, 31, 0, 0))

    print(f"保留有效字符: {kept} 个")
    print(f"新 Bitmaps: {len(new_bm)} 字节, Glyphs: {len(new_gl)} 条目")

    # 生成 .h 文件
    print("生成 cnfont.h...")

    header = f"""// Auto-generated by rebuild_cnfont.py
// 从完整字体 cnfont16pt7b.h 提取 {kept} 个字符
// Source: LXGWWenKaiLite-Regular.ttf 16pt
// 字体名: cnfont_subset16pt8b（保持和代码一致）

const uint8_t cnfont_subset16pt8bBitmaps[] PROGMEM = {{
"""

    # Bitmaps
    bm_lines = []
    for i in range(0, len(new_bm), 12):
        chunk = new_bm[i:i + 12]
        bm_lines.append("  " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
    header += "\n".join(bm_lines) + "\n};\n\n"

    # Glyphs
    header += f"const GFXglyph cnfont_subset16pt8bGlyphs[] PROGMEM = {{\n"
    gl_lines = []
    for i, g in enumerate(new_gl):
        offset, w, h, adv, xo, yo = g
        code = first + i
        comment = ""
        if w > 1:
            try:
                comment = f"  // 0x{code:04X} '{chr(code)}'"
            except ValueError:
                comment = f"  // 0x{code:04X}"
        gl_lines.append(f"  {{ {offset:5d}, {w:2d}, {h:2d}, {adv:2d}, {xo:4d}, {yo:4d} }},{comment}")
    header += "\n".join(gl_lines) + "\n};\n\n"

    # GFXfont
    gfx_end = " };"
    header += (
        "const GFXfont cnfont_subset16pt8b PROGMEM = {\n"
        "  (uint8_t  *)cnfont_subset16pt8bBitmaps,\n"
        "  (GFXglyph *)cnfont_subset16pt8bGlyphs,\n"
        + "  0x" + format(first, 'X') + ", 0x" + format(last, 'X')
        + ", " + str(yAdvance) + gfx_end + "\n\n"
        + "// Approx. " + str(len(new_bm)) + " + " + str(len(new_gl) * 7) + " bytes\n"
    )

    with open(OUTPUT_H, 'w') as f:
        f.write(header)

    import os
    print(f"\n已写入 {OUTPUT_H} ({os.path.getsize(OUTPUT_H)} 字节)")
    print(f"  Bitmaps: {len(new_bm)}B, Glyphs metadata: {len(new_gl) * 7}B")


if __name__ == '__main__':
    main()
